"""initial_empty_schema

Revision ID: fa95eccbeedb
Revises:
Create Date: 2026-09-03 14:50:55.549728

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "fa95eccbeedb"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
